#start
#FROM golang
FROM scratch

#auth
MAINTAINER bayugyug<bayugyug@gmail.com>

#envt

#prepare
ENV PORT 8989
EXPOSE $PORT

#prepare
COPY building-custom-api /

#main entry
ENTRYPOINT [ "/building-custom-api" ]
